version: '3.8'

services:
  whoami-service:
    image: whoami-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8081"
    deploy:
      mode: replicated
      replicas: 10
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/whoami"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - whoami-network

  nginx:
    image: nginx-lb:latest
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    deploy:
      placement:
        constraints: [node.role == manager]
      mode: replicated
      replicas: 1
    depends_on:
      - whoami-service
    networks:
      - whoami-network
      
  visualizer:
    image: custom-visualizer:latest
    build:
      context: .
      dockerfile: Dockerfile.visualizer
    ports:
      - "8080:8080"
    deploy:
      placement:
        constraints: [node.role == manager]
      mode: replicated
      replicas: 1
    networks:
      - whoami-network

networks:
  whoami-network:
    driver: overlay 
